### ISSUE TITLE
Will this bechmark be available?

### ISSUE THREAD

**Issue by mrbeann** [delimitrou/DeathStarBench#1]
As I read in the paper, this benchmark was released in http://microservices.ece.cornell.edu/, but actually, I can't find it, the email address is also broken.

**Comment by cdelimitrou** [comment]
We haven't released it yet. We'll upload the first applications by next week. The email address is currently being set up, but it should work starting tonight.

**Comment by mrbeann** [comment]
Thanks for your reply. This benchmark looks really interesting, hope we can try it soon.

**Comment by mrbeann** [comment]
It seems that one month passed since I asked it last time. Any progress about this benchmark?

**Comment by cdelimitrou** [comment]
The social network is now available, the other applications will also be released shortly.

**Comment by mrbeann** [comment]
Thanks, hope we can see them soon.
