### ISSUE TITLE
The wrk2 console latency is much larger the jaeger tracing latency when the rps is high

### ISSUE THREAD

**Issue by liuzijuan123** [delimitrou/DeathStarBench#10]
Why the wrk2 console latency is much larger the jaeger tracing latency when the rps is high?
The time from client to the nginx shouldn't be so  long.

**Comment by cdelimitrou** [comment]
Please post your setup, i.e., input to wrk2 and configuration for the tiers, so we can try to replicate it.

**Comment by gy1005** [comment]
It is possible that either wrk2 get saturated or NGINX get saturated. Jaeger cannot record the server queueing time in front of NGINX.

**Comment by liuzijuan123** [comment]
The DeathStarBench/socialNetwork is running in one local service with two nodes(numa architecture,each node has 14 cores and 28 logical cores) .And all the microservices of the socialNetworking run in one node except jaeger, the jaeger runs in the other node ,the wrk2 runs in the node which jaeger in, and the configuration of the wrk2 is thread =10,conn=100,duration=30s,rps=2300,the 99% latency is on the order of seconds,But the request I find the largest in the jaeger UI is about 100ms.I am confused about the large gap between two result.

**Comment by cdelimitrou** [comment]
To check if it's the case Yu is describing above, try increasing the resources of the docker container running nginx, and see if the difference between the wrk2 and jaeger end-to-end latency goes down. If it does, then nginx is saturated for the load you are specifying, and you'll need to either give it more resources, or lower the input requests/s.
