### ISSUE TITLE
Hardcoded url in JavaScript of frontend

### ISSUE THREAD

**Issue by Bender250** [delimitrou/DeathStarBench#11]
Hi,

Starting the image using `docker-compose up` lead to frontend having incorrect url in JS code for forms.

`http://localhost:8080/compose.html`

```javascript

function clickEvent(){
    if (document.getElementById('media').value != "") {
        var formData = new FormData(document.getElementById('media-form'));
        const Http = new XMLHttpRequest();
        const url='http://ath-8.ece.cornell.edu:8081/upload-media';
        Http.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                var resp = JSON.parse(Http.responseText);
                uploadPost(resp);
           }
        };

        Http.open("POST", url, true);
        Http.send(formData);
    } else {
        uploadPost()
    }

}
```

Exactly this line:

```javascript
const url='http://ath-8.ece.cornell.edu:8081/upload-media';
```

The same issue is with `function uploadPost` in `compose.html`, in `user-timeline.html` with `clickEvent` - variables `url` and `img.src`, and the same in `home-timeline.html`. Changing the address to const `url='http://localhost:8081/upload-media';` worked in compose - the file was correctly uploaded and stored in the DB.

**Comment by cdelimitrou** [comment]
That's correct, you'll need to change that either to localhost, if you're running all microservices on the same machine, or to the machine address where the target microservice is running.

**Comment by leecalcote** [comment]
@cdelimitrou is the plan to remove these hard-coded names and replace with service names? Doing so will help with Kubernetes compatibility. 

A Meshery community member has the social network app running on Kubernetes now (having converted from docker-compose packaging to Kubernetes manifests), however, the app is dysfunctional given these hard-codings.

**Comment by cdelimitrou** [comment]
Yes, we're working on updating this. 

[reopening issue until it's fixed] @gy1005

**Comment by Panlichen** [comment]
## Try to deploy DeathStarBench on k8s and encounter some dns issuses


I am interested in kubernetes, but there is little access to real workload in the industrial as a student, so DeathStarBench seems quite awesome to me. Given it is originally for docker-compose, I try to transfer it to k8s yamls. I think I almost make it, but there are some issues(which I guess is about dns settings of `yg397/openresty-thrift:xenial` image) I cannot handle, so I am now writing for help.

Kubernetes yaml files for socialNetwork are [here]( https://github.com/Panlichen/DeathStarBench/tree/dev-252/socialNetwork/k8s-yaml ), for mediaMicroservices are [here]( https://github.com/Panlichen/DeathStarBench/tree/dev-252/mediaMicroservices/k8s-yaml ), I write them according to the original relative docker-compose files and service-config.json.  When I `kubectl apply -f` the yamls, it seems they all run smoothly:

![1571138202782](https://user-images.githubusercontent.com/13653578/66831536-7a6d0080-ef8a-11e9-9c91-18b27cd2c0a5.png)


Note that the "service" pods have status running, which means they can access DB services they depends on, such as mongodb or redis, from the k8s cluster. But it seems that the nginx-thrift cannot find any services from the cluster.

When I run `./wrk -D exp -t 1 -c 1 -d 30s -L -s ./scripts/social-network/compose-post.lua http://10.68.184.173:8080/wrk2-api/post/compose -R 20` (`10.68.184.173` is [ClusterIP]( https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types ) of nginx-thrift service), the measured latency is either `0.00us` or `-nanus`, the jaeger UI shows:

<img width="516" alt="clip_image001" src="https://user-images.githubusercontent.com/13653578/66831560-848eff00-ef8a-11e9-9a95-6c90b4375172.png">


Log of the nginx-thrift pod says:

```reStructuredText
# kubectl logs  nginx-thrift-57cd7549c8-mjnwf -c nginx-thrift
2019/10/14 15:01:43 [error] 25#25: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/14 15:01:48 [error] 25#25: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/14 15:01:53 [error] 25#25: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/14 15:01:58 [error] 25#25: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/14 15:02:03 [error] 25#25: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/14 15:02:08 [error] 25#25: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/14 15:02:13 [error] 25#25: *2 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/thrift/Thrift.lua:37: TTransportException: Could not connect to home-timeline-service:9090 (home-timeline-service could not be resolved (110: Operation timed out))
stack traceback:
coroutine 0:
        [C]: in function 'error'
        /usr/local/openresty/lualib/thrift/Thrift.lua:37: in function 'terror'
        /usr/local/openresty/lualib/thrift/TSocket.lua:87: in function 'open'
        /usr/local/openresty/lualib/thrift/RpcClient.lua:30: in function 'init'
        /usr/local/openresty/lualib/thrift/RpcClientFactory.lua:11: in function 'createClient'
        /usr/local/openresty/lualib/thrift/GenericObjectPool.lua:20: in function 'connection'
        ...nresty/nginx/lua-scripts/wrk2-api/home-timeline/read.lua:74: in function 'ReadHomeTimeline'
        content_by_lua(nginx.conf:307):3: in main chunk, client: 172.20.232.0, server: localhost, request: "GET http://localhost:8080/wrk2-api/home-timeline/read?user_id=221&start=85&stop=95 HTTP/1.1", host: "10.68.184.173:8080"
2019/10/15 03:09:18 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:18 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:18 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:18 [error] 9#9: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:23 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:23 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:28 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:28 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:33 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:33 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:38 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:38 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:43 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:43 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:48 [error] 9#9: *5 lua user thread aborted: runtime error: /usr/local/openresty/lualib/thrift/Thrift.lua:37: TTransportException: Could not connect to media-service:9090 (media-service could not be resolved (110: Operation timed out))
stack traceback:
coroutine 0:
        [C]: in function 'error'
        /usr/local/openresty/lualib/thrift/Thrift.lua:37: in function 'terror'
        /usr/local/openresty/lualib/thrift/TSocket.lua:87: in function 'open'
        /usr/local/openresty/lualib/thrift/RpcClient.lua:30: in function 'init'
        /usr/local/openresty/lualib/thrift/RpcClientFactory.lua:11: in function 'createClient'
        /usr/local/openresty/lualib/thrift/GenericObjectPool.lua:20: in function 'connection'
        ...al/openresty/nginx/lua-scripts/wrk2-api/post/compose.lua:67: in function <...al/openresty/nginx/lua-scripts/wrk2-api/post/compose.lua:61>
coroutine 1:
        [C]: in function 'wait'
        ...al/openresty/nginx/lua-scripts/wrk2-api/post/compose.lua:120: in function 'ComposePost'
        content_by_lua(nginx.conf:321):3: in main chunk, client: 172.20.232.0, server: localhost, request: "POST http://localhost:8080/wrk2-api/post/compose HTTP/1.1", host: "10.68.184.173:8080"

```

The log shows it cannot find `home-timeline-service:9090` and `media-service:9090` via resolver `127.0.0.11:53`. 

But when I use `  kubectl exec  nginx-thrift-57cd7549c8-mjnwf -it /bin/bash  ` to enter the pod ,  I get:

```reStructuredText
root@nginx-thrift-57cd7549c8-mjnwf:/# cat /etc/resolv.conf 
nameserver 10.68.0.2
search default.svc.cluster.local. svc.cluster.local. cluster.local.
options ndots:5

root@nginx-thrift-57cd7549c8-mjnwf:/# curl home-timeline-service:9090
curl: (52) Empty reply from server

root@nginx-thrift-57cd7549c8-mjnwf:/# curl media-service:9090 
curl: (52) Empty reply from server
```

I think this means the resolver of the pod is `10.68.0.2`, which is the ClusterIP of core-dns service of the cluster, and it CAN reach `home-timeline-service:9090` and `media-service:9090 ` from inside the pod.

So I guess the strange "``127.0.0.11:53``" resolver may be assigned hard-coded in the image, this [issue]( https://github.com/delimitrou/DeathStarBench/issues/11 ) seems relative.

 I am wondering whether you could help me understand the problem and fix it, I am more than honored if I could work with you to make the awesome work better.

**Comment by Panlichen** [comment]
I find that the strange "`127.0.0.11`" resolver is defined in [`socialNetwork/nginx-web-server/conf/nginx.conf:43`]( https://github.com/delimitrou/DeathStarBench/blob/master/socialNetwork/nginx-web-server/conf/nginx.conf#L43 ) (and another two `nginx.conf` files). I change the resolver IP to `10.68.0.2`, which is the clusterIP of core-dns service of my kubernetes cluster and re-apply all the yamls of socialNetwork. This time, when I run ` ./wrk -D exp -t 1 -c 1 -d 30s -L -s ./scripts/social-network/compose-post.lua http://10.68.110.115:8080/wrk2-api/post/compose -R 20`, where `10.68.110.115` is the new clusterIP of `nginx-thrift` service, the printed latency is more reasonable, but logs of pod `nginx-thrift-57cd7549c8-mqtnr` still shows that it cannot get access to any services. 

Before I change the resolver setting in config file, the related error message in `nginx-thrift ` pod log is 

```reStructuredText
2019/10/15 03:09:43 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2019/10/15 03:09:48 [error] 9#9: *5 lua user thread aborted: runtime error: /usr/local/openresty/lualib/thrift/Thrift.lua:37: TTransportException: Could not connect to media-service:9090 (media-service could not be resolved (110: Operation timed out))
```

which may indicate the resolver is unavailable; by changing the resolver setting, the error message becomes

```reStructuredText
2019/10/16 08:38:01 [error] 14#14: *650 lua user thread aborted: runtime error: /usr/local/openresty/lualib/thrift/Thrift.lua:37: TTransportException: Could not connect to media-service:9090 (media-service could not be resolved (3: Host not found))
```

which may indicate it can connect to the resolver, but cannot get the name "`media-service`" resolved. However, as I mentioned in the previous e-mail, when I use `kubectl exec -it bash` to get into the pod, the name "`media-service`"  CAN be resolved in command line, so can all other service names.

```reStructuredText
root@nginx-thrift-57cd7549c8-mqtnr:/# curl media-service:9090
curl: (52) Empty reply from server

root@nginx-thrift-57cd7549c8-mqtnr:/# curl user-timeline-service:9090
curl: (52) Empty reply from server

root@nginx-thrift-57cd7549c8-mqtnr:/# curl url-shorten-mongodb:27017
It looks like you are trying to access MongoDB over HTTP on the native driver port.
```

Besides, if I just comment out the [resolver line](https://github.com/delimitrou/DeathStarBench/blob/master/socialNetwork/nginx-web-server/conf/nginx.conf#L43 ), the error message in pod log will be

```reStructuredText
2019/10/16 07:46:42 [error] 18#18: *2 lua user thread aborted: runtime error: /usr/local/openresty/lualib/thrift/Thrift.lua:37: TTransportException: Could not connect to media-service:9090 (no resolver defined to resolve "media-service")
```



As far as I can imagine, in docker-compose, every docker has to deal with the issue about dns, so it has to define a resolver; but in kubernetes, the cluster level core-dns will handle all things about dns. When I use  cluster core-dns as the docker resolver, conflicts may happen. But to point it out more clearly and fix it is now beyond my ability, I really need your help.

Sorry to have bothered you.

**Comment by Panlichen** [comment]
With the help of @gy1005 , I solve the dns problem and other issues, then deploy socialNetwork and mediaMicroservices on my k8s cluster of 30+ machines. [Here](https://github.com/delimitrou/DeathStarBench/pull/21#issue-330114044) is the pull request.

**Comment by cdelimitrou** [comment]
Thanks @Panlichen. Pull request merged.
