### ISSUE TITLE
hotelReservation gopkg.in/mgo.v2 failed

### ISSUE THREAD

**Issue by iideas18** [delimitrou/DeathStarBench#112]
sh hotelReservation/scripts/build-docker-images.sh
`package gopkg.in/mgo.v2: unrecognized import path "gopkg.in/mgo.v2" (https fetch: Get https://gopkg.in/mgo.v2?go-get=1: dial tcp 91.189.92.76:443: i/o timeout)
The command '/bin/sh -c go get gopkg.in/mgo.v2' returned a non-zero code: 1
`

![image](https://user-images.githubusercontent.com/44938480/117404658-e92ef780-af3c-11eb-9a77-fa62106d8e4c.png)

**Comment by cherylLbt** [comment]
Could you please tell me how did you address this issue? It seems like a firewall problem. @iideas18
