### ISSUE TITLE
Are all features of social network from paper implemented?

### ISSUE THREAD

**Issue by Bender250** [delimitrou/DeathStarBench#12]
Hi! In the paper, fig. 4 and the corresponding text mentions several features that I do not see running within the image. Can you clarify what is already implemented, what is a plan, and what would not be implemented?

The image supports following 12 binaries:
 * ComposePostService
 * HomeTimelineService
 * MediaService
 * PostStorageService
 * SocialGraphService
 * TextService
 * UniqueIdService
 * UrlShortenService
 * UserMentionService
 * UserService
 * UserTimelineService
 * WriteHomeTimelineService

Which does not map 1:1 to the fig. 4, but I miss at least:
 * Ads
 * User recommender engine
 * Search service
 * User statistics

The following features might be implemented within the existing binaries:
 * Sending messages between users
 * Follow, unfollow and block users
 * Favorite and repost posts

I would like to use your benchmark for something as process mining, so it would be perfect to understand what is happening. And I was not able to understand it from the source code.

Thank you for clarifying this :).

**Comment by cdelimitrou** [comment]
The open-source version does not yet have all the features we implemented internally. The public version should include the search and recommender engine, although @gy1005 can correct me if I'm wrong. The other features you mentioned are implemented internally, but we are still testing them, so they are not committed to the public repo yet. ETA for those to be checked in publicly is the end of summer. 

Feel free to let us know if you have any other questions.
