### ISSUE TITLE
In the docker-compose environment, why does hotelReservation run abnormally and the ip address is abnormal? 

### ISSUE THREAD

**Issue by hty0506** [delimitrou/DeathStarBench#137]
According to the readme configuration environment, the address of the json file was also replaced with the physical address of the machine, but the operation was abnormal.
![image](https://user-images.githubusercontent.com/53992861/134446600-49280e8d-b92d-4908-b509-9c94bcde7490.png)

Jaeger shows an error, only 4 microservices are running, and no ip address can be used. How should I modify it?
![image](https://user-images.githubusercontent.com/53992861/134446659-a752a491-85e0-454a-9961-9faab99d49b5.png)
![image](https://user-images.githubusercontent.com/53992861/134446673-82df3062-3705-4920-bbc2-64124cbba13b.png)

Hope someone can help me!

**Comment by hty0506** [comment]
@lianhao

**Comment by lianhao** [comment]
it works fine in my docker-compose environment. Please make sure you do NOT specify Orchestrator to the value of k8s in config.json. Also please rebuild the docker image 'sudo docker-compose build' after you make any update to the config.json.  Once the pending PR #136  is merged, you don't need to change config.json any more.

**Comment by hty0506** [comment]
> it works fine in my docker-compose environment. Please make sure you do NOT specify Orchestrator to the value of k8s in config.json. Also please rebuild the docker image 'sudo docker-compose build' after you make any update to the config.json. Once the pending PR #136 is merged, you don't need to change config.json any more.

Thank you, it has been resolved. After updating config.json, I did not rebuild the docker image "sudo docker-compose build".
