### ISSUE TITLE
Social Network Development

### ISSUE THREAD

**Issue by Indridcold96** [delimitrou/DeathStarBench#14]
Hi, my name is Luiz Eduardo Magalhães Ferreira, i'm a software engineering student from Brazil, my reason for this contact is to clarify some premises, i'm currently developing a social network and i would like to know if i can use your software architecture as a base and, if so, the specific version that i develop can be associated with a private company, which i intend, in the future, to found. Thta is my only concern, i read the GNU license but some things were not so clear to me, i apologize in advanced for asking something that is already expressively written somewhere, i just want to make sure not to hurt your work, which i'm trully impressed and fascinated by, anyway, thanks for your attention, if you need to talk to me you can contact me here or through my personal email luizeduardo.m.ferreira@gmail.com

**Comment by cdelimitrou** [comment]
Hi Luiz, thanks for your interest in the benchmark suite! As per GPL's guidelines, code that builds on GPL code also needs to be open-sourced. This means that you are free to use the applications internally in your company, e.g., for testing, without needing to open-source any modifications you had to make, but if they would be part of your company's product, then that code would need to be open-sourced under GPL. Hope this helps.

**Comment by cdelimitrou** [comment]
You are welcome to post questions here or in our mailing list: microservices-bench-L@list.cornell.edu
