### ISSUE TITLE
Error with HotelReservation (bug?) 

### ISSUE THREAD

**Issue by krishangpatney** [delimitrou/DeathStarBench#142]
After attempting to use the command sudo docker-compose up -d, this yields the error 
![image](https://user-images.githubusercontent.com/55298813/137112186-14a5701b-be7c-407a-83ea-28dd8f1be170.png)
on both local ubuntu based VMs & AWS based ubuntu VM. 

Has anyone got a fix for this?

**Comment by rkuper** [comment]
Hi, not sure if this is a good fix or not, but try adding this to the beginning of .../hotelReservation/Dockerfile:
`RUN apt update && apt install ca-certificates libgnutls30 -y`
