### ISSUE TITLE
--server-address argument in write_movie_info.py

### ISSUE THREAD

**Issue by varungohil** [delimitrou/DeathStarBench#149]
The "Register users and movie information" section in mediaMicroservices/README.md shows that we need to pass --server-address argument with write_movie_info.py. However, no such argument exists in write_movie_info.py, and it runs correctly without specifying the argument. 

I think the README file needs to be corrected by removing the --server-address argument  in the example.

**Comment by sirius8050** [comment]
I also had the same problem, I solved it. If you deploy mediaService in kubernetes, the address is ths IP address of Pod "Nginx-web-server", and port is 8080. If you deplot it in docker, you should use a IP address that can communicate the container "Nginx".

**Comment by aditya-shrivastava** [comment]
```--server-address http://localhost:8080``` worked for me
