### ISSUE TITLE
Can jaeger tracing be replaced by zipkin?

### ISSUE THREAD

**Issue by JackGzj** [delimitrou/DeathStarBench#16]
Hello, We have written codes based on zipkin span, can the jaeger tracing in the project replaced by zipkin and how?

**Comment by gy1005** [comment]
I am not able to provide technical details here because I didn't have such experience. But I looks to me that Jaeger is [backwards-compatible with Zipkin](https://www.jaegertracing.io/docs/1.13/features/#backwards-compatibility-with-zipkin).

**Comment by JackGzj** [comment]
Thanks and I am going to rewrite part of our codes.

**Comment by JackGzj** [comment]
Excuse me, but is there any guide to deploy the application on Kubernetes?

**Comment by cdelimitrou** [comment]
Yes, take a look at the recent commits on deployment with kubernetes.
