### ISSUE TITLE
socialNetwork out-of-the-box deploys correctly but app is broken

### ISSUE THREAD

**Issue by msimonin** [delimitrou/DeathStarBench#182]
I tried with both: `docker-compose`(single machine) and `docker stack deploy`(swarm cluster).

commit version: 18338e75fb59e214c5a3ab64c8007d26b762847d
yg397/social-network-microservices version : sha256:bafeeccb00a0143b4bcdee3d45ef0286214844a882073a6297b87a3e61b60190

In both cases the deployment runs smoothly but  adding a new post to a freshly created user doesn't work (`docker logs` seems to complain about a redis function `ZADD` but I'm not sure this is the root cause).

As a consequence the `wrk `tool  with the parameter `./scripts/social-network/compose-post.luawrk` doesn't work.

Could you have a look ?

**Comment by mmartin4972** [comment]
same issue here

**Comment by msimonin** [comment]
I had a second try with these parameters:
```
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
memcached                            latest              b033ffae1ea6        2 hours ago         89.2MB
jaegertracing/all-in-one             latest              6fbfab507d6a        2 hours ago         57.7MB
redis                                latest              bba24acba395        39 hours ago        113MB
yg397/social-network-microservices   latest              6faef786a522        6 months ago        1.5GB
mongo                                4.4.6               61ea24dc52c6        8 months ago        423MB
yg397/openresty-thrift               xenial              71414b07488e        11 months ago       617MB
yg397/media-frontend                 xenial              07c94a4ce3df        2 years ago         729MB
```

and code version: ec2b4539c257d7d6ad9228ff881d9af8c05d5ee4


When I log using a fresh user, I try to add a new post. After validating the post, it doesn't show up in the timeline.


![image](https://user-images.githubusercontent.com/2486813/160999221-54f3f6da-6f92-4d85-a893-c8a6d2f05ab5.png)

![image](https://user-images.githubusercontent.com/2486813/160999341-1c827dfe-cb80-45f5-911e-48118bef0559.png)

I don't know what the exact expected behaviour is but this looks weird to me.

**Comment by msimonin** [comment]
@gavinlichn have you had a chance to look at this :point_up_2:  ?

**Comment by gavinlichn** [comment]
The second screenshot should be "home-timeline". it will show the current user followees' post
For example, I'm user2, I followed user1, the home-timeline shows user1's post, NOT user2's

I have verified on my side with docker-compose(single node), it works without problem
![Home-timeline](https://user-images.githubusercontent.com/29390827/162106522-c9f0b4c4-5c4d-41e1-b1f7-916eec79cb99.png)

My steping:

1. register user1 and user2
2. login user1, compose a post (post1)
3. login user2 and follow user1
5. login user1, compost the 2nd post (post2)
6. login user2, check home-timeline
7. post2 will shows


> I had a second try with these parameters:
> 
> ```
> REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
> memcached                            latest              b033ffae1ea6        2 hours ago         89.2MB
> jaegertracing/all-in-one             latest              6fbfab507d6a        2 hours ago         57.7MB
> redis                                latest              bba24acba395        39 hours ago        113MB
> yg397/social-network-microservices   latest              6faef786a522        6 months ago        1.5GB
> mongo                                4.4.6               61ea24dc52c6        8 months ago        423MB
> yg397/openresty-thrift               xenial              71414b07488e        11 months ago       617MB
> yg397/media-frontend                 xenial              07c94a4ce3df        2 years ago         729MB
> ```
> 
> and code version: [ec2b453](https://github.com/delimitrou/DeathStarBench/commit/ec2b4539c257d7d6ad9228ff881d9af8c05d5ee4)
> 
> When I log using a fresh user, I try to add a new post. After validating the post, it doesn't show up in the timeline.
> 
> ![image](https://user-images.githubusercontent.com/2486813/160999221-54f3f6da-6f92-4d85-a893-c8a6d2f05ab5.png)
> 
> ![image](https://user-images.githubusercontent.com/2486813/160999341-1c827dfe-cb80-45f5-911e-48118bef0559.png)
> 
> I don't know what the exact expected behaviour is but this looks weird to me.

**Comment by msimonin** [comment]
Thanks ! That's now clear,  @gavinlichn I reproduced the same as you for both docker and docker/swarm.

I guess the only issue that remains is the one I have with wrk: I'm unable to get statistics out of the tool:

I ran the following on a swarm setup (`10.158.0.2` is the address where the frontend is reachable using the browser):

```bash
root@virtual-158-0-2:/tmp/dsb/socialNetwork/wrk2# ./wrk -D exp -t 1 -c 1 -d 10 -L -s ./scripts/social-network/compose-post.lua http://10.158.0.2:8080/wrk2-api/post/compose -R  1
./scripts/social-network/compose-post.lua: ./scripts/social-network/compose-post.lua:2: attempt to index global 'socket' (a nil value)
./scripts/social-network/compose-post.lua: ./scripts/social-network/compose-post.lua:2: attempt to index global 'socket' (a nil value)
Running 10s test @ http://10.158.0.2:8080/wrk2-api/post/compose
  1 threads and 1 connections
  Thread calibration: mean lat.: 0.963ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     99%   +/- Stdev
    Latency     -nanus    -nanus   0.00us    0.00%
    Req/Sec       -nan      -nan   0.00      0.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    0.00us
 75.000%    0.00us
 90.000%    0.00us
 99.000%    0.00us
 99.900%    0.00us
 99.990%    0.00us
 99.999%    0.00us
100.000%    0.00us

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.000     1.000000            0          inf
#[Mean    =         -nan, StdDeviation   =         -nan]
#[Max     =        0.000, Total count    =            0]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  17 requests in 10.00s, 3.65KB read
  Non-2xx or 3xx responses: 17
Requests/sec:      1.70
Transfer/sec:     373.88B

```

the warning about the `nil` socket sounds weird to me though.

**Comment by gavinlichn** [comment]
Glad to see it resolve your problem.

For the wrk failre, considering it's caused by lua_rocket version upgrading. We can file another issue to track it.
And please clost his issue if no other questions.

> Thanks ! That's now clear, @gavinlichn I reproduced the same as you for both docker and docker/swarm.
> 
> I guess the only issue that remains is the one I have with wrk: I'm unable to get statistics out of the tool:
> 
> I ran the following on a swarm setup (`10.158.0.2` is the address where the frontend is reachable using the browser):
> 
> ```shell
> root@virtual-158-0-2:/tmp/dsb/socialNetwork/wrk2# ./wrk -D exp -t 1 -c 1 -d 10 -L -s ./scripts/social-network/compose-post.lua http://10.158.0.2:8080/wrk2-api/post/compose -R  1
> ./scripts/social-network/compose-post.lua: ./scripts/social-network/compose-post.lua:2: attempt to index global 'socket' (a nil value)
> ./scripts/social-network/compose-post.lua: ./scripts/social-network/compose-post.lua:2: attempt to index global 'socket' (a nil value)
> Running 10s test @ http://10.158.0.2:8080/wrk2-api/post/compose
>   1 threads and 1 connections
>   Thread calibration: mean lat.: 0.963ms, rate sampling interval: 10ms
>   Thread Stats   Avg      Stdev     99%   +/- Stdev
>     Latency     -nanus    -nanus   0.00us    0.00%
>     Req/Sec       -nan      -nan   0.00      0.00%
>   Latency Distribution (HdrHistogram - Recorded Latency)
>  50.000%    0.00us
>  75.000%    0.00us
>  90.000%    0.00us
>  99.000%    0.00us
>  99.900%    0.00us
>  99.990%    0.00us
>  99.999%    0.00us
> 100.000%    0.00us
> 
>   Detailed Percentile spectrum:
>        Value   Percentile   TotalCount 1/(1-Percentile)
> 
>        0.000     1.000000            0          inf
> #[Mean    =         -nan, StdDeviation   =         -nan]
> #[Max     =        0.000, Total count    =            0]
> #[Buckets =           27, SubBuckets     =         2048]
> ----------------------------------------------------------
>   17 requests in 10.00s, 3.65KB read
>   Non-2xx or 3xx responses: 17
> Requests/sec:      1.70
> Transfer/sec:     373.88B
> ```
> 
> the warning about the `nil` socket sounds weird to me though.

**Comment by msimonin** [comment]
Thanks @gavinlichn I'm closing this and open a new one regarding the issue with wrk.
