### ISSUE TITLE
Running Social network on a k8s cluster (without openshift)

### ISSUE THREAD

**Issue by labros-zotos** [delimitrou/DeathStarBench#186]
Is there a way to deploy the social network benchmark on a k8s cluster without using openshift?  
In order for the deployments to work the configmaps are needed but I can't use the scripts without using the OpenShift CLI.

**Comment by swap357** [comment]
Have you tried using helm chart for k8s deployment ?  https://github.com/delimitrou/DeathStarBench/tree/master/socialNetwork/helm-chart

That, i found, is the most convenient way.

**Comment by labros-zotos** [comment]
Thank I haven't seen that there are helm charts for the project. I will try it out

**Comment by Zenghao-CQ** [comment]
> Have you tried

Hi labros, i am trying to deploy social network on k8s too, and i using helm cmd as follow:
``helm install social ./socailnetwork``
And i make svc nginx-thrift a nodeprt, but i can not create any post, did i miss something？
Thx for ur help.
