### ISSUE TITLE
Is there a way to disable jaegar tracing?

### ISSUE THREAD

**Issue by SuvigyaJain1** [delimitrou/DeathStarBench#187]
I need to disable jaegar tracing completely as I am doing microsecond scale latency analysis and want to minimize any such overheads. Is there a reliable way to do this or is there a branch/release of the repo without jaegar which I could use?

**Comment by dmorse76** [comment]
In nginx-web-server/jaeger-config.json, change the sampler "param" from 0.2 to 0.0
