### ISSUE TITLE
k8s HotelReservation the geo service is CrashLoopBackOff

### ISSUE THREAD

**Issue by cherylLbt** [delimitrou/DeathStarBench#190]
I run the Hotel Reservation system based on a k8s cluster on an AWS instance. However, I meet several issues:
1. "authorization failed" when pushing the image when running `kubernetes/scripts/build-docker-images.sh`. I remove the `--push` and continue
2. Then I meet the next issue: the geo service keeps "CrashLoopBackOff". The logs show "TLS disabled".
![截屏2022-04-06 下午8 22 42](https://user-images.githubusercontent.com/49298462/161973380-64a0b2ba-0417-4e72-ba70-71915a86b282.png)
![截屏2022-04-06 下午8 22 54](https://user-images.githubusercontent.com/49298462/161973419-ca880588-6bfd-498d-afec-6067bac03517.png)
"
I follow the guidance and it seems I cannot enable TLS communication inside a k8s cluster. Could you please help me with this problem?

**Comment by sirius8050** [comment]
You should change th setting in (mongodb geo/mongodb user...) Service Yaml, the port is wrong. You can start a container in localhost by docker, then enter the container and execute the command (like 'geo'), you will know which port number the container is requesting.

**Comment by cherylLbt** [comment]
I have solved this problem. Thanks very much. I would like to close this issue.

**Comment by snehithjk** [comment]
@BEbillionaireUSD can you please explain how you solved the issue?
