### ISSUE TITLE
About user import [500 Internet Server Error]and wrk2 unable to find Lua Library

### ISSUE THREAD

**Issue by SSuperMengNan** [delimitrou/DeathStarBench#211]
![image](https://user-images.githubusercontent.com/92978013/177076966-d5fb3291-f080-4620-ab4c-91407f5ef1b7.png)
![NR$OMSV@J`2YO)ZWM@I`B7L](https://user-images.githubusercontent.com/92978013/177076981-93e3ca29-4ec1-4cf4-8878-17a3848810f6.png)

**Comment by SSuperMengNan** [comment]
I can normally require "socket" when using the Lua command, but an error is reported when generating the load。
![image](https://user-images.githubusercontent.com/92978013/177077087-277bfc51-170c-4124-a623-f95e454f26a2.png)

**Comment by SSuperMengNan** [comment]
> It seems you do not have lua-socket installed, what is the output of "dpkg -l lua-socket"? My system shows:
> 
> ```
> # dpkg -l lua-socket
> Desired=Unknown/Install/Remove/Purge/Hold
> | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
> |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
> ||/ Name             Version               Architecture Description
> +++-================-=====================-============-===========================================
> ii  lua-socket:amd64 3.0~rc1+git+ac3201d-6 amd64        TCP/UDP socket library for the Lua language
> ```
> 
> socket.lua should be under your Lua installation directory:
> 
> ```
> # find /usr/local/share/lua |grep socket
> /usr/local/share/lua/5.1/socket.lua
> /usr/local/share/lua/5.1/socket
> /usr/local/share/lua/5.1/socket/smtp.lua
> /usr/local/share/lua/5.1/socket/url.lua
> /usr/local/share/lua/5.1/socket/http.lua
> /usr/local/share/lua/5.1/socket/ftp.lua
> /usr/local/share/lua/5.1/socket/headers.lua
> /usr/local/share/lua/5.1/socket/tp.lua
> ```

Thank you for your help. This problem has been solved. How can I solve the "500 internal server error" of registered users

**Comment by SSuperMengNan** [comment]
> It seems you do not have lua-socket installed, what is the output of "dpkg -l lua-socket"? My system shows:
> 
> ```
> # dpkg -l lua-socket
> Desired=Unknown/Install/Remove/Purge/Hold
> | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
> |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
> ||/ Name             Version               Architecture Description
> +++-================-=====================-============-===========================================
> ii  lua-socket:amd64 3.0~rc1+git+ac3201d-6 amd64        TCP/UDP socket library for the Lua language
> ```
> 
> socket.lua should be under your Lua installation directory:
> 
> ```
> # find /usr/local/share/lua |grep socket
> /usr/local/share/lua/5.1/socket.lua
> /usr/local/share/lua/5.1/socket
> /usr/local/share/lua/5.1/socket/smtp.lua
> /usr/local/share/lua/5.1/socket/url.lua
> /usr/local/share/lua/5.1/socket/http.lua
> /usr/local/share/lua/5.1/socket/ftp.lua
> /usr/local/share/lua/5.1/socket/headers.lua
> /usr/local/share/lua/5.1/socket/tp.lua
> ```

**Comment by SSuperMengNan** [comment]
> 看来你没有安装 lua-socket，“dpkg -l lua-socket”的输出是什么？我的系统显示：
> 
> ```
> # dpkg -l lua-socket
> Desired=Unknown/Install/Remove/Purge/Hold
> | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
> |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
> ||/ Name             Version               Architecture Description
> +++-================-=====================-============-===========================================
> ii  lua-socket:amd64 3.0~rc1+git+ac3201d-6 amd64        TCP/UDP socket library for the Lua language
> ```
> 
> socket.lua 应该在你的 Lua 安装目录下：
> 
> ```
> # find /usr/local/share/lua |grep socket
> /usr/local/share/lua/5.1/socket.lua
> /usr/local/share/lua/5.1/socket
> /usr/local/share/lua/5.1/socket/smtp.lua
> /usr/local/share/lua/5.1/socket/url.lua
> /usr/local/share/lua/5.1/socket/http.lua
> /usr/local/share/lua/5.1/socket/ftp.lua
> /usr/local/share/lua/5.1/socket/headers.lua
> /usr/local/share/lua/5.1/socket/tp.lua
> ```

Thank you for your help. This problem has been solved. How can I solve the "500 internal server error" of registered users

**Comment by dmorse76** [comment]
Please close this issue since it's been resolved and open a new one for that issue
