### ISSUE TITLE
Changing workload

### ISSUE THREAD

**Issue by matnar** [delimitrou/DeathStarBench#22]
I'd like to use the social network scenario to evaluate an autoscaling policy. 

By reading the documentation, I've found that I can send request to the service as follows: 
`./wrk -D exp -t <num-threads> -c <num-conns> -d <duration> -L -s ./scripts/social-network/compose-post.lua http://localhost:8080/wrk2-api/post/compose -R <reqs-per-sec>`

Using this command, the client sends a burst of request to the server at a fixed rate (-R). Is there a way to send requests by following a varying pattern of requests per second?

**Comment by cdelimitrou** [comment]
Yes, you can change the -D parameter. Currently it's for an exponential distribution, but you can change to uniform, etc. Check ./wrk -h for a list of accepted load distributions.

**Comment by matnar** [comment]
where can I read more about the different distribution parameters?

**Comment by gy1005** [comment]
It supports the arrival interval to be 
- Fixed, with `-D fixed`
- Exponential distribution, with `-D exp`, to model Poisson arrival process
- Zipfian distribution, with `-D zipf`, to model heavy-tailed arrival process

The distribution parameters are set according to the rates set with `-R`, and thus, you need to change the work load generator a little bit to model varying load patterns.
