### ISSUE TITLE
Need more detail information about dependencies between containers and files.

### ISSUE THREAD

**Issue by Zhuanghq7** [delimitrou/DeathStarBench#23]
In the past three weeks, our team decided to use socialNetwork to be the bench mark for our research. threrefore, I need to deploy the whole 30 containers in a cluster. Because for the lack of dependencies between containers, I made quite a greate effort before I finally resolve all the errors occured when deploying.

Now, socialNetwork works well in cluster, and next focus on the hotelReservation project.

I recommend that you can describe more detail about the applications such as the dependencies between containers or how configs like the *'config.json'* in hotelReservation work , so the users like me can use your bench mark more easily.

**Comment by cdelimitrou** [comment]
The dependencies are shown in the image in the README file. For any issues you run into, you could have opened an issue here. Same if you run into issues with the other applications.

**Comment by Zhuanghq7** [comment]
> The dependencies are shown in the image in the README file. For any issues you run into, you could have opened an issue here. Same if you run into issues with the other applications.

Which I mean is that the README file is too short and lose many useful information. Like the starting sequence for the services if I want to boot up all the service by **docker run ** instead of *docker-compose up*.

You know, docker-compose is easy and convienient to use but not friendly for testing in some situations.

**Comment by jxc4583** [comment]
Hello, how to deploy the whole 30 containers in a cluster? I need your help.

**Comment by Zhuanghq7** [comment]
> Hello, how to deploy the whole 30 containers in a cluster? I need your help.
First, contain all your containers in one docker swarm, and then create an overlay network in the swarm with anyname you like.
Next, translate all the services in the docker-compose file into command like 'docker run'
Last, use '--net=[your network ]' to let the contianers join your network.
Thats all. Best wishes to you.

**Comment by jxc4583** [comment]
Thanks for your answer. I will try it according to your method.
Are you using WeChat? Can I have your WeChat number?

Thank you again anyway.


------------------ 原始邮件 ------------------
发件人: "Zhuangh7"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 晚上9:48
收件人: "delimitrou/DeathStarBench"<DeathStarBench@noreply.github.com>;
抄送: "JXC"<458385004@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [delimitrou/DeathStarBench] Need more detail information aboutdependencies between containers and files. (#23)



 
Hello, how to deploy the whole 30 containers in a cluster? I need your help.
 First, contain all your containers in one docker swarm, and then create an overlay network in the swarm with anyname you like.
 Next, translate all the services in the docker-compose file into command like 'docker run'
 Last, use '--net=[your network ]' to let the contianers join your network.
 Thats all. Best wishes to you.

**Comment by Fatahir** [comment]
did u successfully execute hotel reservation service?
