### ISSUE TITLE
Version of protoc & protoc-gen-go？

### ISSUE THREAD

**Issue by NaNillll** [delimitrou/DeathStarBench#238]
Hello！
About hotel reservations， which version of protoc & protoc-gen-go is used？It seems the newest protoc can not complied  .proto in project......

**Comment by zWang64** [comment]
I had the same issue. 
It turned out that you should use `github.com/golang/protobuf/protoc-gen-go` instead of `google.golang.org/protobuf/cmd/protoc-gen-go`.
Good luck.

**Comment by NaNillll** [comment]
> 

Thank you. I solve by update all protoc tools and grpc
