### ISSUE TITLE
Is ther any chance to  change DeathStartBench into Serverless mode?

### ISSUE THREAD

**Issue by Zhuanghq7** [delimitrou/DeathStarBench#26]
Hi there,
I try to modify the services into such a situation that, all services is down untile a request is arrive, and the contianers will auto turn up to deal with the request and go to destory after send the response.
Is ther any useful suggestions? Or some others ideas to make the benchmark more flexable and useful!

**Comment by Panlichen** [comment]
I transfered this benchmark to k8s, and Google's serverless platform knative seems base on k8s, you may try it.
