### ISSUE TITLE
socialnetwork_nginx-thrift_1 keeps restarting (image: yg397/openresty-thrift:xenial)

### ISSUE THREAD

**Issue by Luke-WENG** [delimitrou/DeathStarBench#27]
Hi,

I am deploying socialnetwork on a single machine with `docker-compose`. The nginx-thrift (from image: `yg397/openresty-thrift:xenial`) keeps restarting after `docker-compose up` and fails to provide services. The log of the container shows the error as follows,

```bash
2019/10/28 10:44:29 [error] 1#1: init_by_lua error: /gen-lua/social_network_ttypes.lua:31: attempt to index local '__TObject' (a nil value)
stack traceback:
	/gen-lua/social_network_ttypes.lua:31: in main chunk
	[C]: in function 'require'
	/gen-lua/social_network_UserTimelineService.lua:18: in main chunk
	[C]: in function 'require'
	init_by_lua:7: in main chunk
nginx: [error] init_by_lua error: /gen-lua/social_network_ttypes.lua:31: attempt to index local '__TObject' (a nil value)
stack traceback:
	/gen-lua/social_network_ttypes.lua:31: in main chunk
	[C]: in function 'require'
	/gen-lua/social_network_UserTimelineService.lua:18: in main chunk
	[C]: in function 'require'
	init_by_lua:7: in main chunk
```

In addition, I found the port number of nginx is slightly inconsistent throughout the project. Have you decided to settle with `8082:8080` for `nginx`? The [`docker-compose.yml`], [`init_social_graph.py`], and examples in [`README.md`] about `wrk` usage have mentioned the port.

BTW, after issue https://github.com/delimitrou/DeathStarBench/issues/11, will DeathStarBench still support single-node experiments with Docker in the future? Or using Kubernetes is suggested for upcoming benchmarks?

---
- Environment:
  - OS: Ubuntu 18.04
  - docker-compose version: 1.22.0, build f46880fe
- Reproduce:
  - `git clone https://github.com/delimitrou/DeathStarBench.git`
  -  `cd DeathStarBench/socialNetwork`
  - `docker-compose up -d`
  - `docker container ls -a`
---

Thank you.

Best regards,
Luke

[`docker-compose.yml`]: https://github.com/delimitrou/DeathStarBench/blob/master/socialNetwork/docker-compose.yml#L224
[`init_social_graph.py`]: https://github.com/delimitrou/DeathStarBench/blob/master/socialNetwork/scripts/init_social_graph.py#L72
[`README.md`]: https://github.com/delimitrou/DeathStarBench/tree/master/socialNetwork#compose-posts

**Comment by Luke-WENG** [comment]
I have solved the issue by running
```bash
docker pull -a
```

Since the base images have also been updated to the latest version. Now it works perfectly on single node.

Thank you for the efforts and sorry for the bothering.

**Comment by Fatahir** [comment]
@Luke-WENG  my container of social network services does not keep running when i run them individually. #46
