### ISSUE TITLE
 [hoteReservation app] consul default image tag not working - needs to be updated to hashicorp/consul

### ISSUE THREAD

**Issue by chiragcshetty** [delimitrou/DeathStarBench#275]
Consul deployment yaml ([here](https://github.com/delimitrou/DeathStarBench/blob/master/hotelReservation/kubernetes/consul/consul-deployment.yaml)) uses "**image: consul:latest**". Support for this was recently stopped as reported [here](https://github.com/hashicorp/consul/issues/17973). Accordingly, it must be updated to "**image: hashicorp/consul:latest**".

Without this the pod shows " ErrImagePull" when deployed and the app doesn't work.
Thanks.

**Comment by yuhang-lin** [comment]
This happened to me today too.

**Comment by rohitdwivedula** [comment]
On [this issue](https://github.com/hashicorp/consul/issues/17973) on the consul repo, one of the contributors to the repo mentioned this as well: 

> Please use hashicorp/consul:latest instead. We have removed support for official images as per the announcement here: https://github.com/docker-library/docs/pull/2283 and https://github.com/hashicorp/consul/releases/tag/v1.15.0. Will close as this is as designed.
