### ISSUE TITLE
README differs from docker-compose.yml

### ISSUE THREAD

**Issue by rjw245** [delimitrou/DeathStarBench#30]
A change was merged recently that moved nginx servers from port 8080 to 8082, but the documentation was not updated to match.

Can this be fixed?

**Comment by rjw245** [comment]
Also, the default ports in the Python scripts are still 8080

**Comment by Panlichen** [comment]
Sorry to be confusing, it was my fault. My local 8080 was occupied, so I changed it, and forgot to change it back in the PR.
