### ISSUE TITLE
can not run hotel reservation application with docker-compose

### ISSUE THREAD

**Issue by hassanSattariNia** [delimitrou/DeathStarBench#314]
i try to run hotel reservation application after install pre-requirement :
Docker
Docker-compose
luarocks (apt-get install luarocks)
luasocket (luarocks install luasocket)

and write these commands:
docker-compose build

docker-compose up -d

but can not running many of container and failed

**Comment by Red-GV** [comment]
Heya @hassanSattariNia, you may want to see if this helps you: https://github.com/delimitrou/DeathStarBench/issues/320#issuecomment-1893852511
