### ISSUE TITLE
Social network set up problem

### ISSUE THREAD

**Issue by 123toorc** [delimitrou/DeathStarBench#37]
Hi 
    I am working on a project and try to use this benchmark. I noticed that almost all the servers are inside docker containers. I use the wrk2 to run on the port 8080, which gives me the number. I want to make sure it is right since I using elinks to connect to the localhost:8080, which is unavailable but work on port 8082 I believe it is a real server, I can see the post and login, etc. Since using wr2 to run a plane web also will return numbers, I connect to 8082 port also have Nginx workers running. Please tell me which part set up I did wrong? should I open the Nginx server or not and how to set it up?

**Comment by Panlichen** [comment]
This is similar to #30, and I fix it in #38. Sorry for the confusion.
