### ISSUE TITLE
Request of the original Dockerfile of several docker images.

### ISSUE THREAD

**Issue by XXXXIEHF** [delimitrou/DeathStarBench#39]
Hi there,
I am trying to make the benchmark run on the ARM platfrom, therefore I need to rebuild docker images including:

- yg397/social-network-microservices
- yg397/openresty-thrift
- yg397/media-frontend

However, the image history of these images are not enough to rebuild them. There are some confusing sha256 strings in the history, making me cannot rebuild these images.

For example, when I try to rebuild the image `yg397/social-network-microservices` using image history:
```
=> ERROR [2/10] ADD file:c02de920036d851cccaedd7f9ed93d48c960ada8e7e839bd2e79ab7b0d7a12d6 in /                                              0.0s
=> CACHED [3/10] RUN /bin/sh -c set -xe       && echo '#!/bin/sh' > /usr/sbin/policy-rc.d      && echo 'exit 101' >> /usr/sbin/policy-rc.d  0.0s
=> CACHED [4/10] RUN /bin/sh -c rm -rf /var/lib/apt/lists/*                                                                                 0.0s
=> CACHED [5/10] RUN /bin/sh -c mkdir -p /run/systemd     && echo 'docker' > /run/systemd/container                                         0.0s
=> CACHED [6/10] RUN /bin/sh -c apt-get update       && apt-get install -y ca-certificates g++ cmake wget git libmemcached-dev automake bi  0.0s
=> CACHED [7/10] RUN /bin/sh -c ldconfig                                                                                                    0.0s
=> ERROR [8/10] COPY dir:0a51c3cb96020cc5f03775907749b78d69d3326d673b3ab700a82110fe47d959 in /social-network-microservices                  0.0s
------
> [2/10] ADD file:c02de920036d851cccaedd7f9ed93d48c960ada8e7e839bd2e79ab7b0d7a12d6 in /:
------
------
> [8/10] COPY dir:0a51c3cb96020cc5f03775907749b78d69d3326d673b3ab700a82110fe47d959 in /social-network-microservices:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: "/dir:0a51c3cb96020cc5f03775907749b78d69d3326d673b3ab700a82110fe47d959" not found: not found
```

I am wondering could you provide the original Dockerfile? Or tell me how to build these images from Dockerfile?

**Comment by cdelimitrou** [comment]
Have you tried building from source or are you pulling from dockerhub? If you build from source, you can adjust the provided dockerfile to work for ARM.

**Comment by XXXXIEHF** [comment]
So are all the dockerfiles are in the ```/docker/``` folder? As their names are not the exactly same I am not pretty sure.

**Comment by XXXXIEHF** [comment]
So are all the dockerfiles in the ```docker/```? As their name are not exactly the same I am not pretty sure about that.

**Comment by cdelimitrou** [comment]
Yes, all file are there.
