### ISSUE TITLE
Questions about the QPS sensitivity in the cpu frequency

### ISSUE THREAD

**Issue by ehdans06** [delimitrou/DeathStarBench#40]
Hello,
I have several questions after reading your ASPLOS paper and utilizing DeathStarBench.

In Fig 12 in DeathStarBench paper, it seems that the QPS limit without QoS violation (or QPS with the same tail latency) increases faster than the frequency increase. 
To be specific, I think the system's performance increases at most twice when the CPU frequency becomes twice higher. But, in the Social Network graph in Fig 12, it seems that the QPS at 2400MHz is more than twice higher than the QPS at 1200MHz.
I also find out the same tendency after built and executed DeathStarBench.

I'm so curious about the reason.
Can you explain why the QPS limit increases faster than the frequency increase?

**Comment by cdelimitrou** [comment]
That's a good point. Keep in mind that the QPS shown is QPS under the QoS tail latency target, which means that depending on how QoS is set (see the paper for more details on this), a small increase in cpu frequency can result in a non-linear increase in QPS. If you only plot achieved QPS (not under QoS) you will see the result that you are describing.
