### ISSUE TITLE
Languages used in repo vs paper

### ISSUE THREAD

**Issue by jfloff** [delimitrou/DeathStarBench#42]
I was reading through the paper and from Table 1 it's mentioned that e.g. Movie Reviewing application has 20% of lines written in Java. But while browsing the repo it seems that all services are implemented in C++. Has the implementation changed from the time the paper got published? 

Thank you,

**Comment by cdelimitrou** [comment]
Yes, we've reimplemented a few services since the paper was published, so the code breakdown in the paper is not entirely up-to-date. You can get the breakdown from the repo for the most up-to-date stats.

**Comment by jfloff** [comment]
Could you point me to a commit with services implemented in Java? I’m interested in those specially.

Thanks in advanced.
