### ISSUE TITLE
Not able to establish connection between services - Hotel Reservation

### ISSUE THREAD

**Issue by Fatahir** [delimitrou/DeathStarBench#43]
I executed your Hotel Reservation microservice and followed the steps as described. When I generate the load using wrk then all the requests failed and generate 500 http status error. All the generated requests included in "Non 2xx or 3xx responses". I tried to catch the error that is "

rpc error: code = Unavailable desc = there is no address available

"
kindly help me to solve this issue. Also when i checked the traces of services on jaeger then only "jaeger-query" in service block is shown. 
![wrk](https://user-images.githubusercontent.com/33696029/74090605-10471100-4acf-11ea-8647-fc5996cd0af4.png)

**Comment by ratnadeepb** [comment]
Same issue here as well.

**Comment by Fatahir** [comment]
did u resolve this issue? @ratnadeepb

**Comment by zyqCSL** [comment]
https://github.com/delimitrou/DeathStarBench/issues/32#issuecomment-564782040

**Comment by Fatahir** [comment]
@zyqCSL  thats isuue was in config.json file but now the authors update that file and there is no localhost problem in config.json

**Comment by zyqCSL** [comment]
https://github.com/delimitrou/DeathStarBench/blob/master/hotelReservation/config.json#L1-L29

**Comment by ratnadeepb** [comment]
@Fatahir I am still facing this. @zyqCSL yes I did swap out `localhost` with the IP of the base server. In fact, the only service I have been to successfully run so far is the `socialNetwork`.

**Comment by ratnadeepb** [comment]
Here is what I see when I run the test:
```
5990 requests in 30.01s, 1.53MB read
Socket errors: connect 0, read 0, write 0, timeout 1
Non-2xx or 3xx responses: 5990
```

**Comment by Fatahir** [comment]
Any one knows how can i find latency of each request using latency(i) inside the done function? 
![la](https://user-images.githubusercontent.com/33696029/74706839-d3e78380-5239-11ea-8179-6c0898d805c4.png)
