### ISSUE TITLE
Is this an active project?

### ISSUE THREAD

**Issue by VahidMostofi** [delimitrou/DeathStarBench#44]
Hi, 
First of all thanks for this amazing repository, lots of good stuff that would definetly help lots of beginners like me.
But I'm wondering is this an active repository? Are you still supporting this and will you support this in future?

**Comment by gy1005** [comment]
Yes, it is an active repo and we are still maintaining the services in this repo.

**Comment by cdelimitrou** [comment]
Just to add to @gy1005's point; the project is active and we're glad you're finding it useful, however, keep in mind that it is a research prototype under a GPL license, and hence does not have 24/7 support, so replies to issues are not immediate.
