### ISSUE TITLE
Data initialization in Hotel Reservation

### ISSUE THREAD

**Issue by amoghavs** [delimitrou/DeathStarBench#45]
According to issue #41, the database initialization happens at cmd/*/db.go. Is it possible that the database initilization happens in other places too?

I have disabled the default initialization and added some static data in each of the cmd/*/db.go code. I was expecting the code to pick up the static input I fed. But with the rebuilt code, I am still getting a lot of the initialization from before (which I hoped wasn't possible because of commenting the default intialization).

It would be great if a rough program flow could be given on how the service comes up, where the DB is being initialized and how to change the input.

**Comment by zyqCSL** [comment]
For now that's the only place where data initialization happens, otherwise you need to implement the rest api for database management.

I would assume in that case either you didn't restart the db, or didn't use the rebuilt images, or the default data was not completely commented off.

**Comment by amoghavs** [comment]
Ok, thanks for the clarification. Will recheck the changes we made.
