### ISSUE TITLE
Social Network Init Social Graph Script

### ISSUE THREAD

**Issue by Kadle11** [delimitrou/DeathStarBench#47]
Hi,
I am still new to python3's asyncio library.

I am not able to understand why the ```tasks``` list in the functions initializing the nodes and edges is not being reset or cleared after every 200 iterations.

**Comment by gy1005** [comment]
You are correct. We could have cleared the list of `tasks ` every 200 iterations since it will no longer be used in the future.

**Comment by Kadle11** [comment]
Thank you for the clarification.
