### ISSUE TITLE
Load balncing between same containers of Social Network 

### ISSUE THREAD

**Issue by Fatahir** [delimitrou/DeathStarBench#52]
Hi, I am trying to do load balancing between multiple containers of same service using nginx container, like if I want to run another container of Home timeline service then I run it by following command

`sudo docker run -itd --restart always --network socialnetwork_default --entrypoint HomeTimelineService --hostname home-timeline-service yg397/social-network-microservices`

It will run container of home timeline service. My issue is that for load balancing between containers I have to provide ip address and port of that container to nginx.conf file which i dont know. How i do that? Help me for this. If you know a little bit then kindly tell me, Thank you in advance

**Comment by gy1005** [comment]
You can scale out the service with a container orchestration platform such as Docker swarm or Kubernetes. It would do load balancing automatically with its internal routing mesh. You could also bypass the routing mesh and have your own external load balancer such as HAProxy. 

I personally use the routing mesh in Docker swarm for load balancing (https://docs.docker.com/engine/swarm/ingress/).
