### ISSUE TITLE
400 Error with "http://localhost:8080/wrk2-api/post/compose" get request

### ISSUE THREAD

**Issue by mywulin** [delimitrou/DeathStarBench#54]
GET http://localhost:8080/wrk2-api/post/compose
General
Request URL: http://localhost:8080/wrk2-api/post/compose

Request Method: GET

Status Code: 400

**Comment by mywulin** [comment]
I have deployed social network microservices successfully, but when I checked Jaeger via http:/localhost:16686/ , "400" error showed. Then I tried "curl http://localhost:8080/wrk2-api/post/compose" manually by Restape, still get 400 error.

**Comment by Fatahir** [comment]
edit the IP address to localhost in wrk2/scripts/social-network/compose-post.lua

**Comment by mywulin** [comment]
Got it. Thanks. Another question, I have no idea how to use http://localhost:8080/index.html. When I logined with one if registered username, then click Compose  Post, it doesn't respond when I submit socfb-Reed98.mtx

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________

**Comment by mywulin** [comment]
Will social network microservice be supported on centos in the near  future? Thanks

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________

**Comment by cdelimitrou** [comment]
@mywulin as of now we don't have concrete plans to support it on centos, sorry. If you run into specific issues though feel free to post here.

**Comment by gy1005** [comment]
We are still working on the frontend and will release it shortly. You are recommended to use the HTTP APIs for now. We are not planning to support centos, but you are free to build your own images with any base image.
