### ISSUE TITLE
Error with running social network test cases

### ISSUE THREAD

**Issue by mywulin** [delimitrou/DeathStarBench#56]
Take testComposePost.py for example, how should I update socket ip and port ?

```
#socket = TSocket.TSocket("ath-8.ece.cornell.edu", 10001)
socket = TSocket.TSocket("10.151.154.11", 10001)
```
```
python3 testComposePost.py
Could not connect to any of [('10.151.154.11', 10001)]
```
If I updated the port to 8080 (the exposed port of socialnetwork_nginx-thrift_1 container), "TSocket read 0 bytes" error occured.

**Comment by gy1005** [comment]
The tests are not built for the end-to-end test. You need to expose the port of the specific microservice that you want to test and directly connect to it.
