### ISSUE TITLE
How can we get the RPC time

### ISSUE THREAD

**Issue by liuzijuan123** [delimitrou/DeathStarBench#6]
Hello, how can we get the rpc time when we run a service?

**Comment by gy1005** [comment]
If you mean the time spent in the Thrift stack, you could integrate thrift with Opentracing framework. 

Here is one example of Thrift-Java with Opentracing. https://github.com/opentracing-contrib/java-thrift

**Comment by liuzijuan123** [comment]
ok,Thank you!
