### ISSUE TITLE
why does QPS not increase with  more connections and threads for "read home timelines" query?

### ISSUE THREAD

**Issue by mywulin** [delimitrou/DeathStarBench#60]
The CPU utility and IOhas not reached the bottleneck. I got the results below.

```
./wrk -D exp -t 10 -c 1000 -d 120 -L -s ./scripts/social-network/read-home-timeline.lua http://IP:8080/wrk2-api/home-timeline/read -R 1 --timeout 5s
...
  Thread Stats   Avg      Stdev     99%   +/- Stdev
    Latency     0.99m    23.78s    1.65m    66.92%
    Req/Sec     2.18k   195.02     2.40k    66.67%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.10m
 75.000%    1.33m
 90.000%    1.41m
 99.000%    1.65m
 99.900%    1.82m
 99.990%    1.92m
 99.999%    1.96m
100.000%    1.98m
...
----------------------------------------------------------
  2557431 requests in 2.00m, 485.35MB read
  Socket errors: connect 0, read 0, write 0, timeout 11725
Requests/sec:  21317.48
Transfer/sec:      4.05MB
```

So, the average Qps is 2.18k or 21317.48? why does QPS not increase with more connections and threads without any cpu or disk io bottleneck?

Is it possible that the benchmark itself is the bottleneck?

**Comment by cdelimitrou** [comment]
Maintaining many connections has an overhead, so over a certain number of connections, around 1000, you won't see a big improvement in performance. One thing you can do is look into entirely asynchronous RPCs, like gRPC. They still have the overhead of connections, but you can sustain a higher QPS.
