### ISSUE TITLE
[Question] Jaeger sampling policy

### ISSUE THREAD

**Issue by deepaksirone** [delimitrou/DeathStarBench#63]
Hello, I have been using Jaeger for latency measurements of the various services.

What is the default sampling policy used by Jaeger? Can this be changed? Also for benchmarking the performance of the various microservices, what is the best recommended policy?

**Comment by gy1005** [comment]
Hi, the default sampling policy we use is constant sampler. You may want to change it to the probabilistic sampler or adaptive sampler for high load. It can be changed through config/jaeger-config.yml
