### ISSUE TITLE
Internal server error on local k8s cluster while sending requests

### ISSUE THREAD

**Issue by Aliasghar-Rahmanian** [delimitrou/DeathStarBench#74]
Before doing dramatic upgrades in the apps, I used to run the apps on a local K8s cluster and they perfectly worked. After a while I needed to do more experiments with the apps but I realized that the new version for some reasons get **500 Internal Server Error** while sending requests to the app (apps are up and running on a local k8s cluster with virtual box VMs). Would you help us with that? I used those Yaml files for open shift to have them up and running on a local k8s cluster since in the recent upgrades there are no k8s-yaml files same as the prior versions.

**Comment by SuvigyaJain1** [comment]
Were you able to fix this issue? I am facing the same problem

**Comment by zarak-shahjee** [comment]
Same problem here, any fix?
