### ISSUE TITLE
nginx-web-server/UserTimelineService and nginx-web-server/HomeTimelineService's span no finish 

### ISSUE THREAD

**Issue by liuzijuan123** [delimitrou/DeathStarBench#8]
Hi,I find the UserTimelineService span is no fishish in the DeathStarBench/socialNetwork/nginx-web-server/lua-scripts/wrk2-api/user-timeline/read.lua file，And the UserTimelineService span will be very long even if I add the span:finish().

**Comment by liuzijuan123** [comment]
It works normally afterI restart docker-compose.

**Comment by cdelimitrou** [comment]
It might be that you were running out of storage in one/some of the docker containers. You can check this via the docker stats interface. I'd suggest starting with the container for jaeger. If it is indeed running out of resources, increase their allocation with docker -m=XXgb
