### ISSUE TITLE
Nginx web server failing in Media Microservice application

### ISSUE THREAD

**Issue by ravendra10** [delimitrou/DeathStarBench#85]
I have deployed the Media microservice on aws using kubernetes. The Nginx web server pod is failing to mount the persistent volume. I got the following events from the nginx pod:
![nginx_error](https://user-images.githubusercontent.com/32922340/99252125-83d33700-2834-11eb-8f8b-e7d6919cbd34.jpg)

**Comment by wyzksp** [comment]
Hi! I encountered the same problem, did you solve it?

**Comment by ravendra10** [comment]
> Hi! I encountered the same problem, did you solve it?

I think the issue is that the application requires a NFS persistent storage and requires us to change pv and pvc yaml files. I think AWS EFS is the way to go for this.

**Comment by wyzksp** [comment]
Did you succeed? I didn't deployed it on aws, but I used NFS Share on my Kubernetes and it didn't work.

**Comment by ravendra10** [comment]
> Did you succeed? I didn't deployed it on aws, but I used NFS Share on my Kubernetes and it didn't work.

I am still learning how to do it. Meanwhile, can you tell me how to setup NFS share on k8. Any links to refer, etc....

**Comment by ravendra10** [comment]
Got the issue. Need to create configmaps for nginx config files (nginx-k8s.conf)
