### ISSUE TITLE
How to deploy this benchmark with docker swarm or kubernetes?

### ISSUE THREAD

**Issue by blinkbear** [delimitrou/DeathStarBench#9]

**Comment by cdelimitrou** [comment]
We haven't used the apps with docker swarm or kubernetes at the moment, but as long as you pass the containers specified in docker-compose.yml to kubernetes using the init function (see https://kubernetes.io/docs/concepts/workloads/pods/init-containers/), it should work pretty seamlessly.

**Comment by blinkbear** [comment]
Thank you very much, I have successfully deployed this benchmark with Docker Swarm, and now I try to use kubernetes to deploy it.

**Comment by mrbeann** [comment]
Can your share your yaml file for docker swarm? I also try to deploy it, but it seems something abnormal happened. And maybe you can PR to this project. Thanks!

**Comment by girishranganathan** [comment]
@blinkbear, can you please tell us if you were able to deploy this app on Kubernetes?
